version: '3'
services:
    postgres:
      container_name: montage_db
      image: postgres:10.5
      env_file: .env
      ports:
        - "5432:5432"
      volumes:
        - "postgres:/var/lib/postgresql/montage/data"
    web:
        build: .
        container_name: montage_web
        env_file: .env
        command: python manage.py runserver 0.0.0.0:8000 --settings=montage.settings.dev
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        depends_on:
            - postgres
volumes:
  postgres:
