version: '3'
services:
    postgres:
      container_name: montage_db
      image: postgres:10.5
      environment:
        DB_DATABASE:
        DB_USERNAME:
        DB_PASSWORD:
        DB_HOST:
      ports:
        - "5432:5432"
      volumes:
        - db-volume:/var/lib/postgres
    web:
        build: .
        container_name: montage_web
        environment:
          SECRET_KEY:
          DB_DATABASE:
          DB_USERNAME:
          DB_PASSWORD:
          DB_HOST:
          DJANGO_DEBUG:
          DJANGO_LOG_LEVEL:
          PYTHONDEVREQUIRES:
          SOCIAL_AUTH_TWITTER_KEY:
          SOCIAL_AUTH_TWITTER_SECRET:
          MONTAGE_GUNICORN_WORKER:
          DJANGO_SETTINGS_MODULE:
          CLOUDINARY_UPLOAD_FOLDER:
          CLOUDINARY_CLOUD_NAME:
          CLOUDINARY_API_KEY:
          CLOUDINARY_API_SECRET:
          MGT_CLIENT_ID:
          MGT_CLIENT_ID_SECRET:
          AUTH0_API_IDENTIFIER:
          AUTH0_DOMAIN:
        command:
          - "python"
          - "manage.py"
          - "runserver"
          - "0.0.0.0:8000"
        volumes:
          - toxdir:/var/www/montage/.tox
          - toxdir:/var/www/montage/.pytest_cache
          - .:/var/www/montage
        ports:
            - "8000:8000"
        depends_on:
            - postgres
        stdin_open: true
        tty: true
    nginx:
      container_name: montage_nginx
      image: nginx
      ports:
        - "80:80"
      volumes:
        - "./nginx/:/etc/nginx/"
      depends_on:
        - web
volumes:
  postgres:

volumes:
  db-volume:
  toxdir:
